-- Supabase setup for AI Resume Analyzer API
-- This script supports anon/publishable-key writes for MVP usage.
-- For production, prefer SUPABASE_SERVICE_ROLE_KEY in backend env.

-- 1) Core tables
create table if not exists public.resumes (
  id bigint generated by default as identity primary key,
  raw_text text not null,
  created_at timestamptz default now()
);

create table if not exists public.analysis (
  id bigint generated by default as identity primary key,
  resume_id bigint references public.resumes(id) on delete cascade,
  score numeric not null,
  skills jsonb not null,
  missing_skills jsonb not null,
  suggestions jsonb not null,
  created_at timestamptz default now()
);

create index if not exists idx_analysis_resume_id on public.analysis(resume_id);

-- 2) Storage bucket
insert into storage.buckets (id, name, public)
values ('resumes', 'resumes', false)
on conflict (id) do nothing;

-- 3) Grants for anon/authenticated roles
grant usage on schema public to anon, authenticated;
grant insert, select on table public.resumes to anon, authenticated;
grant insert, select on table public.analysis to anon, authenticated;
grant usage, select on sequence public.resumes_id_seq to anon, authenticated;
grant usage, select on sequence public.analysis_id_seq to anon, authenticated;

-- 4) Enable RLS
alter table public.resumes enable row level security;
alter table public.analysis enable row level security;

-- 5) Table policies (MVP open insert/select)
drop policy if exists "resume_insert_anon" on public.resumes;
create policy "resume_insert_anon"
on public.resumes
for insert
to anon, authenticated
with check (true);

drop policy if exists "resume_select_anon" on public.resumes;
create policy "resume_select_anon"
on public.resumes
for select
to anon, authenticated
using (true);

drop policy if exists "analysis_insert_anon" on public.analysis;
create policy "analysis_insert_anon"
on public.analysis
for insert
to anon, authenticated
with check (true);

drop policy if exists "analysis_select_anon" on public.analysis;
create policy "analysis_select_anon"
on public.analysis
for select
to anon, authenticated
using (true);

-- 6) Storage policies for resumes bucket
drop policy if exists "resumes_bucket_insert_anon" on storage.objects;
create policy "resumes_bucket_insert_anon"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'resumes');

drop policy if exists "resumes_bucket_select_anon" on storage.objects;
create policy "resumes_bucket_select_anon"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'resumes');
